version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    container_name: my_postgres
    ports:
      - 5435:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sriboga_arus
      - TZ=Asia/Jakarta